algoritmo "areadoquadrado"
// Função : Solicitar o valor da área do quadrado
// Autor :  Gabriel Moraes
// Data : 01/05/2020
// Seção de Declarações 
var
lado: REAL
total: REAL

inicio
// Central de Dados ETEC
escreval("------------------------------------------------------------------------------------------------")
escreval("-----------------------------Central de Dados ETEC----------------------------------------------")
escreval("------------------------------------------------------------------------------------------------")

//Entrada
escreval("Digite o valor do lado de seu quadrado:")
leia(lado)

//Processamento
total <- (lado*lado)

//Saída
escreval("A área de seu quadrado é:",total)

escreval("-------------------------------------------------------------------------------------------")
escreval("--------------------------Obrigado por escolher ETEC----------------------------------------------")
escreval("-------------------------------------------------------------------------------------------")
fimalgoritmo
