algoritmo "somadosquadrados"
// Função : Calcular a soma dos números ao quadrado
// Autor :  Gabriel Moraes
// Data : 06/05/2020
// Seção de Declarações 
var
n1,n2,n3,n4,total: REAL

inicio
//Central de Dados ETEC
escreval("------------------------------------------------------------------------------------------------")
escreval("-----------------------------Central de Dados ETEC----------------------------------------------")
escreval("------------------------------------------------------------------------------------------------")
// Entrada
escreval("Digite o primeiro número:")
leia(n1)
escreval("Digite o segundo número:")
leia(n2)
escreval("Digite o terceiro número:")
leia(n3)
escreval("Digite o quarto número:")
leia(n4)

//Processamento
total<- n1^2+n2^2+n3^2+n4^2

//Saída
escreval("A soma do quadrado dos seus quatro números é:", total)

escreval("-------------------------------------------------------------------------------------------")
escreval("--------------------------Obrigado por escolher ETEC----------------------------------------------")
escreval("-------------------------------------------------------------------------------------------")

fimalgoritmo
